In [1]:
%load_ext autoreload
%autoreload 2

# Importing required modules and subpackages

In [20]:
from datetime import datetime, timedelta
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
mpl.rcParams["font.size"] = 12

In [21]:
from oceanicospy.observations import AQUAlogger,RBR
from oceanicospy.analysis import temporal

# Pressure data

In [22]:
measurement_pressure_sensors_paths = ['../data/observations/AQ/','../data/observations/RBR/']

sampling_AQ = dict(anchoring_depth=1,sensor_height=0.2,sampling_freq=1,burst_length_s=2048,temperature=False,
                            start_time=datetime(2025,5,9,10,0,0),end_time=datetime(2025,5,19,18,0,0)-timedelta(seconds=1))
sampling_RBR = dict(anchoring_depth=1,sensor_height=0.2,sampling_freq=2,burst_length_s=7200,
                            start_time=datetime(2025,5,9,10,0,0),end_time=datetime(2025,5,19,18,0,0)-timedelta(seconds=0.5))

In [23]:
sampling_data = [sampling_AQ,sampling_RBR]
metadata_list=['AQ','RBR']
dict_raw_measurements = dict()
dict_clean_measurements = dict()

for idx,measurement_path in enumerate(measurement_pressure_sensors_paths):
    if 'AQ' in measurement_path:
        object_device = AQUAlogger(measurement_path, sampling_data[idx])
    else:
        object_device = RBR(measurement_path,sampling_data[idx])

    raw_data = object_device.get_raw_records()
    clean_data = object_device.get_clean_records()
    dict_raw_measurements[metadata_list[idx]] = raw_data
    dict_clean_measurements[metadata_list[idx]] = clean_data

In [24]:
dict_clean_measurements['AQ']

                     pressure[bar]  Raw2  ...  burstId    eta[m]
date                                      ...
2025-05-09 10:00:00       1.245722     0  ...        1  0.052596
2025-05-09 10:00:01       1.244709     0  ...        1  0.041052
2025-05-09 10:00:02       1.237181     0  ...        1 -0.044874
2025-05-09 10:00:03       1.243695     0  ...        1  0.029503
2025-05-09 10:00:04       1.253249     0  ...        1  0.138170
...                            ...   ...  ...      ...       ...
2025-05-19 16:34:03       1.239498     0  ...      124 -0.003209
2025-05-19 16:34:04       1.242248     0  ...      124  0.028177
2025-05-19 16:34:05       1.237905     0  ...      124 -0.021427
2025-05-19 16:34:06       1.243406     0  ...      124  0.041363
2025-05-19 16:34:07       1.239063     0  ...      124 -0.008213

[253952 rows x 6 columns]

In [25]:
TemporalAnalyzer = temporal.WaveTemporalAnalyzer(dict_clean_measurements['AQ'], sampling_data[0])

In [27]:
TemporalAnalyzer.compute_params_from_zero_upcrossing()

                     pressure[bar]  Raw2  ...  burstId    eta[m]
date                                      ...
2025-05-09 10:00:00       0.004536   0.0  ...      0.0  0.052596
2025-05-09 10:00:01       0.003523   0.0  ...      0.0  0.041052
2025-05-09 10:00:02      -0.004005   0.0  ...      0.0 -0.044874
2025-05-09 10:00:03       0.002509   0.0  ...      0.0  0.029503
2025-05-09 10:00:04       0.012063   0.0  ...      0.0  0.138170
...                            ...   ...  ...      ...       ...
2025-05-09 10:34:03       0.000483   0.0  ...      0.0  0.004783
2025-05-09 10:34:04       0.003088   0.0  ...      0.0  0.034496
2025-05-09 10:34:05      -0.001109   0.0  ...      0.0 -0.013396
2025-05-09 10:34:06      -0.002557   0.0  ...      0.0 -0.029934
2025-05-09 10:34:07      -0.007479   0.0  ...      0.0 -0.086254

[2048 rows x 6 columns]
[Timestamp('2025-05-09 10:00:00')]
                     pressure[bar]  Raw2  ...  burstId    eta[m]
date                                      ...
2025-05-09 12:00:00      -0.002277   0.0  ...      0.0 -0.029994
2025-05-09 12:00:01      -0.000684   0.0  ...      0.0 -0.011799
2025-05-09 12:00:02      -0.001408   0.0  ...      0.0 -0.020062
2025-05-09 12:00:03      -0.005896   0.0  ...      0.0 -0.071383
2025-05-09 12:00:04      -0.007777   0.0  ...      0.0 -0.092938
...                            ...   ...  ...      ...       ...
2025-05-09 12:34:03       0.006988   0.0  ...      0.0  0.083768
2025-05-09 12:34:04       0.003513   0.0  ...      0.0  0.044211
2025-05-09 12:34:05      -0.003580   0.0  ...      0.0 -0.036763
2025-05-09 12:34:06      -0.005606   0.0  ...      0.0 -0.059949
2025-05-09 12:34:07      -0.004738   0.0  ...      0.0 -0.050004

[2048 rows x 6 columns]
[Timestamp('2025-05-09 10:00:00'), Timestamp('2025-05-09 12:00:00')]

                         H1/3     Tmean
time
2025-05-09 10:00:00  0.019724  5.407411
2025-05-09 12:00:00  0.020191  5.180165